[project]
name = "poc-weasyprint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crawl4ai>=0.8.0",
    "ipdb>=0.13.13",
    "pdfkit>=1.0.0",
    "playwright>=1.57.0",
    "weasyprint>=68.0",
]
